name: Build Dotnet Core Project

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - review_requested
      - ready_for_review
    branches: [ '*' ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    if: >
      github.event.pull_request.base.ref == 'develop' ||
      (github.event.pull_request.base.ref == 'qa' && 
      github.event.pull_request.reviews.nodes[0].state == 'APPROVED') ||
      (github.event.pull_request.base.ref == 'staging' && 
      contains(github.event.pull_request.reviews.nodes[*].author.login, 'ebsi-snair') &&
      github.event.pull_request.reviews.nodes[0].state == 'APPROVED')
    
    concurrency:
      group: ${{ github.ref }}

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Merge pull request
      uses: pascalgn/automerge-action@v0.11.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
