name: Build Dotnet Core Project

on:
  workflow_call
  
jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build --configuration  Release
