name: Run BPF

on:
  pull_request:
    types:
      - opened 
      - edited
      - reopened      
      - assigned
      - unassigned
      - review_requested
      - ready_for_review
      - review_request_removed
      - synchronize     
    branches: [ '*' ]
    
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Run Webhook
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const response = await octokit.pulls.listReviews({
              owner: owner,
              repo: repo,
              pull_number: prNumber
            });
            
            console.log(response.data);
            
      
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"
#       - run: echo ${{ github.event.review.state }}
      
  bpf:
    runs-on: ubuntu-latest
    
    if: >
      github.event.pull_request.base.ref == 'develop' ||
      (github.event.pull_request.base.ref == 'qa' && 
      github.event.review.state == 'approved') ||
      (github.event.pull_request.base.ref == 'staging' && 
      contains(github.event.pull_request.reviews.nodes[*].author.login, 'ebsi-snair') &&
      github.event.review.state == 'approved')

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      
    - name: Run BPF
      uses: actions/github-script@v6 
      with:
        script: |
          console.log('BPF ran successfully!!')
