name: Run BPF

on:
  pull_request:
    types:
      - opened 
      - edited
      - reopened      
      - assigned
      - unassigned
      - review_requested
      - ready_for_review
      - review_request_removed
      - synchronize     
    branches: [ '*' ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    if: >
      github.event.pull_request.base.ref == 'develop' ||
      (github.event.pull_request.base.ref == 'qa' && 
      github.event.pull_request.reviews.nodes[0].state == 'APPROVED') ||
      (github.event.pull_request.base.ref == 'staging' && 
      contains(github.event.pull_request.reviews.nodes[*].author.login, 'ebsi-snair') &&
      github.event.pull_request.reviews.nodes[0].state == 'APPROVED')

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      
    - name: Run BPF
      uses: actions/github-script@v6 
      with:
        script: |
          console.log('BPF ran successfully!!')
