name: Run BPF

on:
  pull_request:
    types:
      - opened 
      - edited
      - reopened      
      - assigned
      - unassigned
      - review_requested
      - ready_for_review
      - review_request_removed
      - synchronize     
    branches: [ '*' ]
    
  
jobs:
  debug:
    runs-on: ubuntu-latest           
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - run: echo ${{ github.event.review.state }}
      
  bpf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      
    - name: Check approval
      id: review_approval
      run: |
        PR_NUM=${{ github.event.pull_request.number }}
        RESPONSE=$(curl --request GET \
          --url "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUM}/reviews" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json")
          
        echo "$RESPONSE"
          
        APPROVED=$(echo "$RESPONSE" | jq 'map(select(.state == "APPROVED")) | length')
      
        echo "pr_approved=$APPROVED" >> $GITHUB_ENV
      
    - name: Run BPF
      if: >
        github.event.pull_request.base.ref == 'develop' ||
        (github.event.pull_request.base.ref == 'qa' && 
        env.pr_approved == '1') ||
        (github.event.pull_request.base.ref == 'staging' && 
        env.pr_approved == '1')
      uses: actions/github-script@v6 
      with:
        script: |
          console.log('BPF ran successfully!!')
